name: Jest Test Runner

on:
  push:
    branches:
      - dev-all-naveed
  pull_request:
    branches:
      - dev-all
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  equip-test:
    name: Run Equip
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/Equip/package-lock.json"

      - name: Install Shared Deps
        working-directory: backend/LambdaFunctionAPIs/shared
        run: npm install

      - name: Install Test Deps
        working-directory: backend/LambdaFunctionAPIs/Equip
        run: npm install

      - name: Run Jest Tests
        working-directory: backend/LambdaFunctionAPIs/Equip
        run: npm test

  get-all-items-test:
    name: Run GetAllItems
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/GetAllItems/package-lock.json"

      - name: Install Shared Deps
        working-directory: backend/LambdaFunctionAPIs/shared
        run: npm install

      - name: Install Test Deps
        working-directory: backend/LambdaFunctionAPIs/GetAllItems
        run: npm install

      - name: Run Jest Tests
        working-directory: backend/LambdaFunctionAPIs/GetAllItems
        run: npm test

  get-user-items-test:
    name: Run GetUserItems
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/GetUserItems/package-lock.json"

      - name: Install Shared Deps
        working-directory: backend/LambdaFunctionAPIs/shared
        run: npm install

      - name: Install Test Deps
        working-directory: backend/LambdaFunctionAPIs/GetUserItems
        run: npm install

      - name: Run Jest Tests
        working-directory: backend/LambdaFunctionAPIs/GetUserItems
        run: npm test

  high-score-test:
    name: Run HighScore
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/HighScore/package-lock.json"

      - name: Install Shared Deps
        working-directory: backend/LambdaFunctionAPIs/shared
        run: npm install

      - name: Install Test Deps
        working-directory: backend/LambdaFunctionAPIs/HighScore
        run: npm install

      - name: Run Jest Tests
        working-directory: backend/LambdaFunctionAPIs/HighScore
        run: npm test

  leaderboard-test:
    name: Run Leaderboard
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/Leaderboard/package-lock.json"

      - name: Install Shared Deps
        working-directory: backend/LambdaFunctionAPIs/shared
        run: npm install

      - name: Install Test Deps
        working-directory: backend/LambdaFunctionAPIs/Leaderboard
        run: npm install

      - name: Run Jest Tests
        working-directory: backend/LambdaFunctionAPIs/Leaderboard
        run: npm test

  login-test:
    name: Run Login
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/Login/package-lock.json"

      - name: Install Shared Deps
        working-directory: backend/LambdaFunctionAPIs/shared
        run: npm install

      - name: Install Test Deps
        working-directory: backend/LambdaFunctionAPIs/Login
        run: npm install

      - name: Run Jest Tests
        working-directory: backend/LambdaFunctionAPIs/Login
        run: npm test

  score-upload-test:
    name: Run ScoreUpload
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/ScoreUpload/package-lock.json"

      - name: Install Shared Deps
        working-directory: backend/LambdaFunctionAPIs/shared
        run: npm install

      - name: Install Test Deps
        working-directory: backend/LambdaFunctionAPIs/ScoreUpload
        run: npm install

      - name: Run Jest Tests
        working-directory: backend/LambdaFunctionAPIs/ScoreUpload
        run: npm test

