name: Jest Test Runner

on:
  push:
    branches:
      - dev-all-naveed
  pull_request:
    branches:
      - dev-all
      - master-all

jobs:
  test:
    name: Setup AWS Credentials
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: abhilash1in/aws-secrets-manager-action@v2.1.0
        with:
          secrets: |
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY

      - name: Check if env variable is set after fetching secrets
        run: if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then echo "AWS_ACCESS_KEY_ID is unset"; else echo "AWS_ACCESS_KEY_ID is set"; fi

  # test:
  #   name: Run GetAllItems
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/GetAllItems/package-lock.json"
  #
  #     - name: Install Shared Deps
  #       working-directory: backend/LambdaFunctionAPIs/shared
  #       run: npm install
  #
  #     - name: Install Test Deps
  #       working-directory: backend/LambdaFunctionAPIs/GetAllItems
  #       run: npm install
  #
  #     - name: Run Jest Tests
  #       working-directory: backend/LambdaFunctionAPIs/GetAllItems
  #       run: npm test
  #
