name: Jest Test Runner

on:
  push:
    branches:
      - dev-all-naveed
  pull_request:
    branches:
      - dev-all
      - master-all

jobs:
  test:
    name: Run Equip
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: "backend/LambdaFunctionAPIs/Equip/package-lock.json"

      - name: Install Deps
        run: |
          cd backend/LambdaFunctionAPIs/Equip
          npm install

      - name: Run Jest Tests
        run: |
          cd backend/LambdaFunctionAPIs/Equip
          npm test

  # test:
  #   name: Run GetAllItems
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/GetAllItems/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/GetAllItems
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/GetAllItems
  #         npm test
  #
  # test:
  #   name: Run GetItemsByCategory
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/GetItemsByCategory/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/GetItemsByCategory
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/GetItemsByCategory
  #         npm test
  #
  # test:
  #   name: Run GetUserItems
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/GetUserItems/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/GetUserItems
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/GetUserItems
  #         npm test
  #
  # test:
  #   name: Run HighScore
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/HighScore/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/HighScore
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/HighScore
  #         npm test
  #
  # test:
  #   name: Run Leaderboard
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/Leaderboard/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/Leaderboard
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/Leaderboard
  #         npm test
  #
  # test:
  #   name: Run Login
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/Login/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/Login
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/Login
  #         npm test
  #
  # test:
  #   name: Run Purchase
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/Purchase/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/Purchase
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/Purchase
  #         npm test
  #
  # test:
  #   name: Run ScoreUpload
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: npm
  #         cache-dependency-path: "backend/LambdaFunctionAPIs/ScoreUpload/package-lock.json"
  #
  #     - name: Install Deps
  #       run: |
  #         cd backend/LambdaFunctionAPIs/ScoreUpload
  #         npm install
  #
  #     - name: Run Jest Tests
  #       run: |
  #         cd backend/LambdaFunctionAPIs/ScoreUpload
  #         npm test
