name: Unity Test Runner

on: 
  push:
    branches: 
      - dev-all-ethan
      - dev-all-rishi
      - dev-all-rohan
  pull_request:
    branches:
      - dev-all
      - master-all

jobs:
  test:
    name: Run Unity Tests
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: ./ 
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        unityVersion: 2022.3.42f1
